"""add token model

Revision ID: 00073b209596
Revises: 1492a5c8fcc2
Create Date: 2025-11-13 22:04:20.328747

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "00073b209596"
down_revision: str | None = "1492a5c8fcc2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
