"""basic models

Revision ID: 99db91c7e266
Revises: 276611520c40
Create Date: 2025-11-21 16:41:57.540280

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "99db91c7e266"
down_revision: str | None = "276611520c40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
